# Generated by Django 6.0.7 on 2026-07-29 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_asset_last_changed_at'),
        ('webconfig', '0009_alter_webconfigsource_kind_apachevhost_nginxvhost'),
    ]

    operations = [
        migrations.CreateModel(
            name='JeusContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_name', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('listen_port', models.CharField(blank=True, max_length=20)),
                ('ssl_port', models.CharField(blank=True, max_length=20)),
                ('deployed_apps_summary', models.TextField(blank=True)),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jeus_containers', to='core.asset')),
            ],
        ),
        migrations.CreateModel(
            name='JeusWebtobConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('registration_id', models.CharField(blank=True, max_length=100)),
                ('network_address', models.CharField(blank=True, max_length=255)),
                ('port', models.CharField(blank=True, max_length=20)),
                ('wjp_version', models.CharField(blank=True, max_length=20)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webtob_connectors', to='was.jeuscontainer')),
                ('webtob_server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jeus_connectors', to='webconfig.webtobserver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WasConfigSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('jeus8', 'JEUS 8')], max_length=20)),
                ('raw_content', models.TextField()),
                ('last_pushed_at', models.DateTimeField(auto_now=True)),
                ('solution_version', models.CharField(blank=True, max_length=50)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='was_configs', to='core.asset')),
            ],
        ),
        migrations.AddField(
            model_name='jeuscontainer',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='was.wasconfigsource'),
        ),
        migrations.CreateModel(
            name='WasConfigSourceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_content', models.TextField()),
                ('new_content', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='was.wasconfigsource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='wasconfigsource',
            constraint=models.UniqueConstraint(fields=('asset', 'kind'), name='unique_was_config_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='jeuscontainer',
            constraint=models.UniqueConstraint(fields=('source', 'name'), name='unique_jeus_container_name_per_source'),
        ),
    ]
