# Generated by Django 6.0.7 on 2026-07-31 11:23

import django.db.models.deletion
from django.db import migrations, models


def migrate_service_name_to_service(apps, schema_editor):
    """webconfig의 동명 데이터 마이그레이션과 같은 이유 - 같은 이름 문자열은 webconfig 쪽과도
    같은 core.Service 행을 가리켜야 WebToB<->JEUS 서비스 전파가 성립한다."""
    Service = apps.get_model("core", "Service")
    JeusContainer = apps.get_model("was", "JeusContainer")

    service_by_name: dict[str, int] = {}
    names = (
        JeusContainer.objects.exclude(service_name="")
        .values_list("service_name", flat=True)
        .distinct()
    )
    for name in names:
        name = name.strip()
        if not name:
            continue
        if name not in service_by_name:
            service, _ = Service.objects.get_or_create(name=name)
            service_by_name[name] = service.id
        JeusContainer.objects.filter(service_name=name).update(service_id=service_by_name[name])


def noop_reverse(apps, schema_editor):
    """webconfig 쪽 동명 마이그레이션과 같은 이유 - 손실 없이 되감을 원본 문자열이 없다."""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service'),
        ('was', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeuscontainer',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jeus_containers', to='core.service'),
        ),
        migrations.RunPython(migrate_service_name_to_service, noop_reverse),
        migrations.RemoveField(
            model_name='jeuscontainer',
            name='service_name',
        ),
    ]
