# Generated by Django 6.0.7 on 2026-08-06 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('was', '0004_alter_wasconfigsource_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='JeusDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source_id', models.CharField(max_length=100)),
                ('export_name', models.CharField(blank=True, max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=50)),
                ('db_host', models.CharField(blank=True, max_length=255)),
                ('port', models.CharField(blank=True, max_length=20)),
                ('database_name', models.CharField(blank=True, max_length=100)),
                ('db_user', models.CharField(blank=True, max_length=100)),
                ('pool_min', models.PositiveIntegerField(blank=True, null=True)),
                ('pool_max', models.PositiveIntegerField(blank=True, null=True)),
                ('containers', models.ManyToManyField(blank=True, related_name='data_sources', to='was.jeuscontainer')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='was.wasconfigsource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'data_source_id'), name='unique_jeus_datasource_per_source')],
            },
        ),
    ]
