# Generated by Django 6.0.7 on 2026-08-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('was', '0005_jeusdatasource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasconfigsource',
            name='kind',
            field=models.CharField(choices=[('jeus', 'JEUS'), ('jeus6', 'JEUS6')], max_length=20),
        ),
    ]
