# Generated by Django 6.0.7 on 2026-08-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service'),
        ('was', '0006_alter_wasconfigsource_kind'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wasconfigsource',
            name='unique_was_config_per_kind',
        ),
        migrations.AddField(
            model_name='wasconfigsource',
            name='instance_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='wasconfigsource',
            constraint=models.UniqueConstraint(fields=('asset', 'kind', 'instance_name'), name='unique_was_config_per_instance'),
        ),
    ]
