# Generated by Django 6.0.7 on 2026-08-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('was', '0007_remove_wasconfigsource_unique_was_config_per_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasconfigsource',
            name='config_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
