# Generated by Django 6.0.7 on 2026-08-14 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
        ('was', '0008_wasconfigsource_config_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeusdatasource',
            name='db_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jeus_data_sources', to='database.dbinstance'),
        ),
    ]
