# Generated by Django 6.0.7 on 2026-08-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('was', '0009_jeusdatasource_db_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasconfigsource',
            name='kind',
            field=models.CharField(choices=[('jeus', 'JEUS'), ('jeus6', 'JEUS6'), ('tomcat', 'Tomcat')], max_length=20),
        ),
    ]
