# Generated by Django 6.0.7 on 2026-08-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_dbconfigsource_manual_services'),
        ('network', '0001_initial'),
        ('was', '0010_alter_wasconfigsource_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeuscontainer',
            name='manual_db_sources',
            field=models.ManyToManyField(blank=True, related_name='manual_jeus_containers', to='database.dbconfigsource'),
        ),
        migrations.AddField(
            model_name='jeuscontainer',
            name='manual_routes',
            field=models.ManyToManyField(blank=True, related_name='jeus_containers', to='network.networkroute'),
        ),
    ]
