{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cmdb-core.fullname" . }}
  labels:
    {{- include "cmdb-core.labels" . | nindent 4 }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.django.secretKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
  AWX_API_KEY: {{ .Values.awx.apiKey | quote }}
{{- end }}
