# Generated by Django 6.0.7 on 2026-07-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_changed_at',
            field=models.DateTimeField(blank=True, help_text='승인 대상 필드의 변경이 승인되어 반영된 시각', null=True),
        ),
    ]
