# Generated by Django 6.0.7 on 2026-08-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='manual_services',
            field=models.ManyToManyField(blank=True, related_name='manual_assets', to='core.service'),
        ),
    ]
