# Generated by Django 6.0.7 on 2026-08-19 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNetworkMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_domain', models.CharField(blank=True, help_text='외부망 서비스만 해당 (예: www.example.com)', max_length=255)),
                ('external_ip', models.CharField(blank=True, help_text='외부 공인 IP (외부망 서비스만 해당)', max_length=255)),
                ('internal_vip', models.CharField(blank=True, help_text='내부 VIP (L4/로드밸런서 가상 IP)', max_length=255)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network_mapping', to='core.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceNetworkBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_or_hostname', models.CharField(max_length=255)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_backend_entries', to='core.asset')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backends', to='network.servicenetworkmapping')),
            ],
            options={
                'ordering': ['ip_or_hostname'],
            },
        ),
    ]
