# Generated by Django 6.0.7 on 2026-08-24 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_asset_manual_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='이 경로를 찾는 값 - 도메인 또는 VIP (예: www.example.com, 10.0.0.1). Apache/Nginx의 ProxyPass 대상 텍스트에 이 값이 포함되면 구성도에서 자동으로 연결됩니다.', max_length=255, unique=True)),
                ('label', models.CharField(blank=True, help_text='구분용 이름 (예: WEB, GW) - 참고용, 검색/매칭에는 안 쓰임', max_length=100)),
                ('note', models.CharField(blank=True, help_text='비고', max_length=255)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='NetworkRouteBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_or_hostname', models.CharField(max_length=255)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_backend_entries', to='core.asset')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backends', to='network.networkroute')),
            ],
            options={
                'ordering': ['ip_or_hostname'],
            },
        ),
    ]
