# Generated by Django 6.0.7 on 2026-08-20 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asset_manual_services'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicenetworkmapping',
            options={'ordering': ['hop_order']},
        ),
        migrations.AddField(
            model_name='servicenetworkmapping',
            name='hop_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicenetworkmapping',
            name='label',
            field=models.CharField(blank=True, help_text='이 구간을 구분하는 이름 (예: WEB, GW)', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicenetworkmapping',
            name='external_domain',
            field=models.CharField(blank=True, help_text='외부망 구간만 해당 (예: www.example.com)', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicenetworkmapping',
            name='external_ip',
            field=models.CharField(blank=True, help_text='외부 공인 IP (외부망 구간만 해당)', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicenetworkmapping',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_mappings', to='core.service'),
        ),
        migrations.AddConstraint(
            model_name='servicenetworkmapping',
            constraint=models.UniqueConstraint(fields=('service', 'hop_order'), name='unique_hop_order_per_service'),
        ),
    ]
