# Generated by Django 6.0.7 on 2026-07-15 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='raw_facts 안의 dot-path, 예: ansible_facts.ansible_memtotal_mb', max_length=255, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('bool', 'Boolean')], max_length=10)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_searchable', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HostFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('os_family', models.CharField(blank=True, max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=100)),
                ('source_platform', models.CharField(blank=True, choices=[('vcenter', 'vCenter'), ('nutanix', 'Nutanix'), ('physical', 'Physical'), ('unknown', 'Unknown')], max_length=20, null=True)),
                ('vm_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('cluster_name', models.CharField(blank=True, max_length=255, null=True)),
                ('power_state', models.CharField(blank=True, max_length=50, null=True)),
                ('num_cpu', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_facts', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hostfact', to='core.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostFactValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=500, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facts.factfielddefinition')),
                ('host_fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='facts.hostfact')),
            ],
            options={
                'indexes': [models.Index(fields=['field_definition', 'value_text'], name='facts_hostf_field_d_555bd7_idx'), models.Index(fields=['field_definition', 'value_number'], name='facts_hostf_field_d_600fc0_idx')],
                'constraints': [models.UniqueConstraint(fields=('host_fact', 'field_definition'), name='unique_host_fact_field')],
            },
        ),
    ]
