# Generated by Django 6.0.7 on 2026-07-16 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asset_last_changed_at'),
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('fixed', '고정 컬럼'), ('dynamic', '동적 필드')], max_length=10)),
                ('key', models.CharField(help_text='fixed: HostFact 고정 컬럼명 / dynamic: FactFieldDefinition.key와 동일한 값', max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('bool', 'Boolean')], max_length=10)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_type', 'key'), name='unique_approval_field')],
            },
        ),
        migrations.CreateModel(
            name='PendingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_value_text', models.CharField(blank=True, max_length=500, null=True)),
                ('old_value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('old_value_date', models.DateField(blank=True, null=True)),
                ('new_value_text', models.CharField(blank=True, max_length=500, null=True)),
                ('new_value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('new_value_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '반려')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.CharField(blank=True, max_length=150)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_changes', to='core.asset')),
                ('field_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_changes', to='facts.approvalfieldconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
