# Generated by Django 6.0.7 on 2026-07-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0002_approvalfieldconfig_pendingchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='factfielddefinition',
            name='source',
            field=models.CharField(choices=[('auto', '자동 (raw facts 승격)'), ('manual', '수기 입력')], default='auto', max_length=10),
        ),
        migrations.AlterField(
            model_name='factfielddefinition',
            name='key',
            field=models.CharField(help_text='AUTO: raw_facts 안의 dot-path, 예: ansible_facts.ansible_memtotal_mb / MANUAL: raw_facts와 무관한 고유 식별자', max_length=255, unique=True),
        ),
    ]
