# Generated by Django 6.0.7 on 2026-07-23 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0003_factfielddefinition_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalfieldconfig',
            name='value_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('bool', 'Boolean'), ('choice', '선택형')], max_length=10),
        ),
        migrations.AlterField(
            model_name='factfielddefinition',
            name='value_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('bool', 'Boolean'), ('choice', '선택형')], max_length=10),
        ),
        migrations.CreateModel(
            name='FactFieldChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='facts.factfielddefinition')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('field_definition', 'value'), name='unique_field_choice')],
            },
        ),
    ]
