# Generated by Django 6.0.7 on 2026-07-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0007_remove_approvalfieldconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='factfielddefinition',
            name='os_family_key_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='AUTO 필드 전용(선택). os_family(예: Windows/RedHat/AIX)별로 key와 다른 경로를 써야 할 때만 그 os_family만 채움 — 값이 같은 os_family는 안 넣어도 되고, 그 경우 key(기본 경로)를 그대로 씀. 예: {"Windows": "ansible_facts.distribution"} (distribution_version이 리눅스는 사람이 읽는 버전이지만 윈도우는 커널 빌드번호라서, key=ansible_facts.distribution_version을 기본으로 두고 Windows만 이렇게 재정의)'),
        ),
        migrations.AlterField(
            model_name='factfielddefinition',
            name='key',
            field=models.CharField(help_text='AUTO: raw_facts 안의 dot-path(os_family_key_overrides에 없는 os_family는 이 경로를 씀), 예: ansible_facts.ansible_memtotal_mb / MANUAL: raw_facts와 무관한 고유 식별자 / FIXED: HostFact 고정 컬럼명(facts.approval.FIXED_FIELD_EXTRACTORS 참고)', max_length=255, unique=True),
        ),
    ]
