# Generated by Django 6.0.7 on 2026-08-10 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service'),
        ('facts', '0010_alter_factfielddefinition_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factfielddefinition',
            name='requires_approval',
        ),
        migrations.AlterField(
            model_name='factfielddefinition',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='factfielddefinition',
            name='key',
            field=models.CharField(help_text='AUTO: raw_facts 안의 dot-path(os_family_key_overrides에 없는 os_family는 이 경로를 씀), 예: ansible_facts.ansible_memtotal_mb. 경로 중간에 JSON 리스트가 나오면 숫자 인덱스로 진입 가능(예: ansible_facts.interfaces.0.macaddress) - 조건 필터링은 지원 안 함 / MANUAL: raw_facts와 무관한 고유 식별자', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='factfielddefinition',
            name='source',
            field=models.CharField(choices=[('auto', '자동 (raw facts 승격)'), ('manual', '수기 입력')], default='auto', max_length=10),
        ),
        migrations.CreateModel(
            name='FactChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_key', models.CharField(max_length=255)),
                ('field_label', models.CharField(max_length=255)),
                ('old_value', models.CharField(blank=True, max_length=500)),
                ('new_value', models.CharField(blank=True, max_length=500)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_changes', to='core.asset')),
            ],
            options={
                'verbose_name_plural': 'Fact change histories',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.DeleteModel(
            name='PendingChange',
        ),
    ]
