from django.contrib.auth.views import LogoutView
from django.urls import path

from dashboard.views import (
    ApacheVhostListView,
    ApacheVhostServiceUpdateView,
    AssetExportView,
    AssetFactsDetailView,
    AssetListAPIView,
    AssetListView,
    AssetManualFieldUpdateView,
    BulkPendingChangeDecisionView,
    ChangeHistoryListView,
    DashboardLoginView,
    JeusContainerListView,
    JeusContainerServiceUpdateView,
    ManualFieldImportConfirmView,
    ManualFieldImportView,
    NginxVhostListView,
    NginxVhostServiceUpdateView,
    PendingChangeDecisionView,
    ProcessDetailView,
    ProcessListView,
    ServiceExportView,
    ServiceImportConfirmView,
    ServiceImportView,
    WasConfigDetailView,
    WasConfigHistoryListView,
    WasConfigListView,
    WebConfigDetailView,
    WebConfigHistoryListView,
    WebConfigListView,
    WebServiceDomainServiceUpdateView,
    WebServiceListView,
    WebtobVhostListView,
    WebtobVhostServiceUpdateView,
)

urlpatterns = [
    path("login/", DashboardLoginView.as_view(), name="dashboard-login"),
    path("logout/", LogoutView.as_view(), name="dashboard-logout"),
    path("assets/", AssetListView.as_view(), name="dashboard-asset-list"),
    path("assets/<int:pk>/facts/", AssetFactsDetailView.as_view(), name="dashboard-asset-facts"),
    path(
        "assets/<int:pk>/manual-fields/",
        AssetManualFieldUpdateView.as_view(),
        name="dashboard-asset-manual-fields-update",
    ),
    path("assets/export/", AssetExportView.as_view(), name="dashboard-asset-export"),
    path("assets/import/", ManualFieldImportView.as_view(), name="dashboard-asset-import"),
    path(
        "assets/import/confirm/",
        ManualFieldImportConfirmView.as_view(),
        name="dashboard-asset-import-confirm",
    ),
    path("changes/", ChangeHistoryListView.as_view(), name="dashboard-change-history"),
    path(
        "changes/bulk-approve/",
        BulkPendingChangeDecisionView.as_view(action="approve"),
        name="dashboard-change-bulk-approve",
    ),
    path(
        "changes/bulk-reject/",
        BulkPendingChangeDecisionView.as_view(action="reject"),
        name="dashboard-change-bulk-reject",
    ),
    path(
        "changes/<int:pk>/approve/",
        PendingChangeDecisionView.as_view(action="approve"),
        name="dashboard-change-approve",
    ),
    path(
        "changes/<int:pk>/reject/",
        PendingChangeDecisionView.as_view(action="reject"),
        name="dashboard-change-reject",
    ),
    path("webconfig/", WebConfigListView.as_view(), name="dashboard-webconfig-list"),
    path("webconfig/changes/", WebConfigHistoryListView.as_view(), name="dashboard-webconfig-history"),
    path("webconfig/vhosts/", WebtobVhostListView.as_view(), name="dashboard-webtob-vhost-list"),
    path("webconfig/apache/vhosts/", ApacheVhostListView.as_view(), name="dashboard-apache-vhost-list"),
    path("webconfig/nginx/vhosts/", NginxVhostListView.as_view(), name="dashboard-nginx-vhost-list"),
    path("webconfig/<int:pk>/", WebConfigDetailView.as_view(), name="dashboard-webconfig-detail"),
    path(
        "webconfig/vhost/<int:pk>/service/",
        WebtobVhostServiceUpdateView.as_view(),
        name="dashboard-webconfig-vhost-service",
    ),
    path(
        "webconfig/apache/vhost/<int:pk>/service/",
        ApacheVhostServiceUpdateView.as_view(),
        name="dashboard-apache-vhost-service",
    ),
    path(
        "webconfig/nginx/vhost/<int:pk>/service/",
        NginxVhostServiceUpdateView.as_view(),
        name="dashboard-nginx-vhost-service",
    ),
    path("services/", WebServiceListView.as_view(), name="dashboard-webservice-list"),
    path("services/export/", ServiceExportView.as_view(), name="dashboard-service-export"),
    path("services/import/", ServiceImportView.as_view(), name="dashboard-service-import"),
    path(
        "services/import/confirm/",
        ServiceImportConfirmView.as_view(),
        name="dashboard-service-import-confirm",
    ),
    path(
        "services/<int:pk>/service/",
        WebServiceDomainServiceUpdateView.as_view(),
        name="dashboard-webservice-update",
    ),
    path("processes/", ProcessListView.as_view(), name="dashboard-process-list"),
    path("processes/<int:pk>/", ProcessDetailView.as_view(), name="dashboard-process-detail"),
    path("was/", WasConfigListView.as_view(), name="dashboard-was-list"),
    path("was/changes/", WasConfigHistoryListView.as_view(), name="dashboard-was-history"),
    path("was/jeus8/containers/", JeusContainerListView.as_view(), name="dashboard-jeus8-container-list"),
    path("was/<int:pk>/", WasConfigDetailView.as_view(), name="dashboard-was-detail"),
    path(
        "was/jeus8/container/<int:pk>/service/",
        JeusContainerServiceUpdateView.as_view(),
        name="dashboard-jeus8-container-service",
    ),
]

api_urlpatterns = [
    path("assets/", AssetListAPIView.as_view(), name="api-asset-list"),
]
