from django.contrib.auth.views import LogoutView
from django.urls import path

from dashboard.views import (
    ApacheVhostExportView,
    ApacheVhostListView,
    AssetDetailView,
    AssetExportView,
    AssetListAPIView,
    AssetListView,
    AssetManualFieldUpdateView,
    AssetManualServiceUpdateView,
    ChangeHistoryExportView,
    ChangeHistoryListView,
    DashboardLoginView,
    DbConfigDetailView,
    DbConfigExportView,
    DbConfigHistoryExportView,
    DbConfigHistoryListView,
    DbConfigImportConfirmView,
    DbConfigImportView,
    DbConfigListView,
    DbConfigManualFieldUpdateView,
    DbConfigManualServiceUpdateView,
    DbInstanceExportView,
    DbInstanceListView,
    JeusContainerExportView,
    JeusContainerListView,
    ManualFieldImportConfirmView,
    ManualFieldImportView,
    NginxVhostExportView,
    NginxVhostListView,
    OverviewDrilldownView,
    OverviewView,
    ProcessDetailView,
    ProcessExportView,
    ProcessListView,
    ServiceContainerUpdateView,
    ServiceCreateView,
    ServiceDeleteView,
    ServiceExportView,
    ServiceImportConfirmView,
    ServiceImportView,
    ServiceManageListView,
    ServiceNetworkListView,
    ServiceNetworkMappingCreateView,
    ServiceNetworkMappingDeleteView,
    ServiceNetworkMappingUpdateView,
    ServiceRenameView,
    ServiceTopologyView,
    SystemDetailView,
    SystemHostExportView,
    SystemHostImportConfirmView,
    SystemHostImportView,
    SystemHostManualCreateView,
    SystemHostManualDeleteView,
    SystemHostManualFieldUpdateView,
    SystemHostManualServiceUpdateView,
    SystemHostManualUpdateView,
    SystemListView,
    TomcatContainerExportView,
    TomcatContainerListView,
    WasConfigExportView,
    WasConfigDetailView,
    WasConfigHistoryExportView,
    WasConfigHistoryListView,
    WasConfigListView,
    WebConfigDetailView,
    WebConfigExportView,
    WebConfigHistoryExportView,
    WebConfigHistoryListView,
    WebConfigListView,
    WebServiceDomainServiceUpdateView,
    WebServiceListView,
    WebtobVhostExportView,
    WebtobVhostListView,
)

urlpatterns = [
    path("", OverviewView.as_view(), name="dashboard-overview"),
    path("overview/drilldown/", OverviewDrilldownView.as_view(), name="dashboard-overview-drilldown"),
    path("login/", DashboardLoginView.as_view(), name="dashboard-login"),
    path("logout/", LogoutView.as_view(), name="dashboard-logout"),
    path("assets/", AssetListView.as_view(), name="dashboard-asset-list"),
    path("assets/<int:pk>/", AssetDetailView.as_view(), name="dashboard-asset-detail"),
    path(
        "assets/<int:pk>/manual-fields/",
        AssetManualFieldUpdateView.as_view(),
        name="dashboard-asset-manual-fields-update",
    ),
    path(
        "assets/<int:pk>/manual-services/",
        AssetManualServiceUpdateView.as_view(),
        name="dashboard-asset-manual-services-update",
    ),
    path("assets/export/", AssetExportView.as_view(), name="dashboard-asset-export"),
    path("assets/import/", ManualFieldImportView.as_view(), name="dashboard-asset-import"),
    path(
        "assets/import/confirm/",
        ManualFieldImportConfirmView.as_view(),
        name="dashboard-asset-import-confirm",
    ),
    path("changes/", ChangeHistoryListView.as_view(), name="dashboard-change-history"),
    path("changes/export/", ChangeHistoryExportView.as_view(), name="dashboard-change-history-export"),
    path("webconfig/", WebConfigListView.as_view(), name="dashboard-webconfig-list"),
    path("webconfig/export/", WebConfigExportView.as_view(), name="dashboard-webconfig-export"),
    path("webconfig/changes/", WebConfigHistoryListView.as_view(), name="dashboard-webconfig-history"),
    path(
        "webconfig/changes/export/",
        WebConfigHistoryExportView.as_view(),
        name="dashboard-webconfig-history-export",
    ),
    path("webconfig/vhosts/", WebtobVhostListView.as_view(), name="dashboard-webtob-vhost-list"),
    path(
        "webconfig/vhosts/export/",
        WebtobVhostExportView.as_view(),
        name="dashboard-webtob-vhost-export",
    ),
    path("webconfig/apache/vhosts/", ApacheVhostListView.as_view(), name="dashboard-apache-vhost-list"),
    path(
        "webconfig/apache/vhosts/export/",
        ApacheVhostExportView.as_view(),
        name="dashboard-apache-vhost-export",
    ),
    path("webconfig/nginx/vhosts/", NginxVhostListView.as_view(), name="dashboard-nginx-vhost-list"),
    path(
        "webconfig/nginx/vhosts/export/",
        NginxVhostExportView.as_view(),
        name="dashboard-nginx-vhost-export",
    ),
    path("webconfig/<int:pk>/", WebConfigDetailView.as_view(), name="dashboard-webconfig-detail"),
    path("services/", WebServiceListView.as_view(), name="dashboard-webservice-list"),
    path("services/manage/", ServiceManageListView.as_view(), name="dashboard-service-manage"),
    path("services/create/", ServiceCreateView.as_view(), name="dashboard-service-create"),
    path("services/<int:pk>/rename/", ServiceRenameView.as_view(), name="dashboard-service-rename"),
    path("services/<int:pk>/delete/", ServiceDeleteView.as_view(), name="dashboard-service-delete"),
    path("services/topology/", ServiceTopologyView.as_view(), name="dashboard-service-topology"),
    path("services/export/", ServiceExportView.as_view(), name="dashboard-service-export"),
    path("services/import/", ServiceImportView.as_view(), name="dashboard-service-import"),
    path(
        "services/import/confirm/",
        ServiceImportConfirmView.as_view(),
        name="dashboard-service-import-confirm",
    ),
    path(
        "services/<int:pk>/service/",
        WebServiceDomainServiceUpdateView.as_view(),
        name="dashboard-webservice-update",
    ),
    path(
        "services/container/<int:pk>/service/",
        ServiceContainerUpdateView.as_view(),
        name="dashboard-service-container-update",
    ),
    path(
        "services/<int:pk>/network/create/",
        ServiceNetworkMappingCreateView.as_view(),
        name="dashboard-service-network-create",
    ),
    path(
        "network/mapping/<int:pk>/",
        ServiceNetworkMappingUpdateView.as_view(),
        name="dashboard-service-network-update",
    ),
    path(
        "network/mapping/<int:pk>/delete/",
        ServiceNetworkMappingDeleteView.as_view(),
        name="dashboard-service-network-delete",
    ),
    path("processes/", ProcessListView.as_view(), name="dashboard-process-list"),
    path("processes/export/", ProcessExportView.as_view(), name="dashboard-process-export"),
    path("processes/<int:pk>/", ProcessDetailView.as_view(), name="dashboard-process-detail"),
    path("was/", WasConfigListView.as_view(), name="dashboard-was-list"),
    path("was/export/", WasConfigExportView.as_view(), name="dashboard-was-export"),
    path("was/changes/", WasConfigHistoryListView.as_view(), name="dashboard-was-history"),
    path(
        "was/changes/export/",
        WasConfigHistoryExportView.as_view(),
        name="dashboard-was-history-export",
    ),
    path("was/jeus/containers/", JeusContainerListView.as_view(), name="dashboard-jeus-container-list"),
    path(
        "was/jeus/containers/export/",
        JeusContainerExportView.as_view(),
        name="dashboard-jeus-container-export",
    ),
    path(
        "was/tomcat/containers/",
        TomcatContainerListView.as_view(),
        name="dashboard-tomcat-container-list",
    ),
    path(
        "was/tomcat/containers/export/",
        TomcatContainerExportView.as_view(),
        name="dashboard-tomcat-container-export",
    ),
    path("was/<int:pk>/", WasConfigDetailView.as_view(), name="dashboard-was-detail"),
    path("database/", DbConfigListView.as_view(), name="dashboard-db-config-list"),
    path("database/export/", DbConfigExportView.as_view(), name="dashboard-db-config-export"),
    path("database/import/", DbConfigImportView.as_view(), name="dashboard-db-config-import"),
    path(
        "database/import/confirm/",
        DbConfigImportConfirmView.as_view(),
        name="dashboard-db-config-import-confirm",
    ),
    path("database/changes/", DbConfigHistoryListView.as_view(), name="dashboard-db-config-history"),
    path(
        "database/changes/export/",
        DbConfigHistoryExportView.as_view(),
        name="dashboard-db-config-history-export",
    ),
    path("database/instances/", DbInstanceListView.as_view(), name="dashboard-db-instance-list"),
    path(
        "database/instances/export/",
        DbInstanceExportView.as_view(),
        name="dashboard-db-instance-export",
    ),
    path("database/<int:pk>/", DbConfigDetailView.as_view(), name="dashboard-db-config-detail"),
    path(
        "database/<int:pk>/manual-fields/",
        DbConfigManualFieldUpdateView.as_view(),
        name="dashboard-db-config-manual-fields-update",
    ),
    path(
        "database/<int:pk>/manual-services/",
        DbConfigManualServiceUpdateView.as_view(),
        name="dashboard-db-config-manual-services-update",
    ),
    path("systems/", SystemListView.as_view(), name="dashboard-system-list"),
    path("systems/<int:pk>/", SystemDetailView.as_view(), name="dashboard-system-detail"),
    path(
        "systems/<int:pk>/manual-fields/",
        SystemHostManualFieldUpdateView.as_view(),
        name="dashboard-system-manual-fields-update",
    ),
    path(
        "systems/<int:pk>/manual-services/",
        SystemHostManualServiceUpdateView.as_view(),
        name="dashboard-system-manual-services-update",
    ),
    path(
        "systems/physical/create/",
        SystemHostManualCreateView.as_view(),
        name="dashboard-system-physical-create",
    ),
    path(
        "systems/<int:pk>/physical/update/",
        SystemHostManualUpdateView.as_view(),
        name="dashboard-system-physical-update",
    ),
    path(
        "systems/<int:pk>/physical/delete/",
        SystemHostManualDeleteView.as_view(),
        name="dashboard-system-physical-delete",
    ),
    path("systems/export/", SystemHostExportView.as_view(), name="dashboard-system-export"),
    path("systems/import/", SystemHostImportView.as_view(), name="dashboard-system-import"),
    path(
        "systems/import/confirm/",
        SystemHostImportConfirmView.as_view(),
        name="dashboard-system-import-confirm",
    ),
    path("network/", ServiceNetworkListView.as_view(), name="dashboard-network-list"),
]

api_urlpatterns = [
    path("assets/", AssetListAPIView.as_view(), name="api-asset-list"),
]
