from django.contrib.auth.views import LogoutView
from django.urls import path

from dashboard.views import (
    ApacheVhostExportView,
    ApacheVhostListView,
    AssetDetailView,
    AssetExportView,
    AssetListAPIView,
    AssetListView,
    AssetManualFieldUpdateView,
    BulkPendingChangeDecisionView,
    ChangeHistoryExportView,
    ChangeHistoryListView,
    DashboardLoginView,
    JeusContainerExportView,
    JeusContainerListView,
    ManualFieldImportConfirmView,
    ManualFieldImportView,
    NginxVhostExportView,
    NginxVhostListView,
    OverviewDrilldownView,
    OverviewView,
    PendingChangeDecisionView,
    ProcessDetailView,
    ProcessExportView,
    ProcessListView,
    ServiceContainerUpdateView,
    ServiceExportView,
    ServiceImportConfirmView,
    ServiceImportView,
    SystemDetailView,
    SystemHostExportView,
    SystemHostImportConfirmView,
    SystemHostImportView,
    SystemHostManualFieldUpdateView,
    SystemListView,
    WasConfigExportView,
    WasConfigDetailView,
    WasConfigHistoryExportView,
    WasConfigHistoryListView,
    WasConfigListView,
    WebConfigDetailView,
    WebConfigExportView,
    WebConfigHistoryExportView,
    WebConfigHistoryListView,
    WebConfigListView,
    WebServiceDomainServiceUpdateView,
    WebServiceListView,
    WebtobVhostExportView,
    WebtobVhostListView,
)

urlpatterns = [
    path("", OverviewView.as_view(), name="dashboard-overview"),
    path("overview/drilldown/", OverviewDrilldownView.as_view(), name="dashboard-overview-drilldown"),
    path("login/", DashboardLoginView.as_view(), name="dashboard-login"),
    path("logout/", LogoutView.as_view(), name="dashboard-logout"),
    path("assets/", AssetListView.as_view(), name="dashboard-asset-list"),
    path("assets/<int:pk>/", AssetDetailView.as_view(), name="dashboard-asset-detail"),
    path(
        "assets/<int:pk>/manual-fields/",
        AssetManualFieldUpdateView.as_view(),
        name="dashboard-asset-manual-fields-update",
    ),
    path("assets/export/", AssetExportView.as_view(), name="dashboard-asset-export"),
    path("assets/import/", ManualFieldImportView.as_view(), name="dashboard-asset-import"),
    path(
        "assets/import/confirm/",
        ManualFieldImportConfirmView.as_view(),
        name="dashboard-asset-import-confirm",
    ),
    path("changes/", ChangeHistoryListView.as_view(), name="dashboard-change-history"),
    path("changes/export/", ChangeHistoryExportView.as_view(), name="dashboard-change-history-export"),
    path(
        "changes/bulk-approve/",
        BulkPendingChangeDecisionView.as_view(action="approve"),
        name="dashboard-change-bulk-approve",
    ),
    path(
        "changes/bulk-reject/",
        BulkPendingChangeDecisionView.as_view(action="reject"),
        name="dashboard-change-bulk-reject",
    ),
    path(
        "changes/<int:pk>/approve/",
        PendingChangeDecisionView.as_view(action="approve"),
        name="dashboard-change-approve",
    ),
    path(
        "changes/<int:pk>/reject/",
        PendingChangeDecisionView.as_view(action="reject"),
        name="dashboard-change-reject",
    ),
    path("webconfig/", WebConfigListView.as_view(), name="dashboard-webconfig-list"),
    path("webconfig/export/", WebConfigExportView.as_view(), name="dashboard-webconfig-export"),
    path("webconfig/changes/", WebConfigHistoryListView.as_view(), name="dashboard-webconfig-history"),
    path(
        "webconfig/changes/export/",
        WebConfigHistoryExportView.as_view(),
        name="dashboard-webconfig-history-export",
    ),
    path("webconfig/vhosts/", WebtobVhostListView.as_view(), name="dashboard-webtob-vhost-list"),
    path(
        "webconfig/vhosts/export/",
        WebtobVhostExportView.as_view(),
        name="dashboard-webtob-vhost-export",
    ),
    path("webconfig/apache/vhosts/", ApacheVhostListView.as_view(), name="dashboard-apache-vhost-list"),
    path(
        "webconfig/apache/vhosts/export/",
        ApacheVhostExportView.as_view(),
        name="dashboard-apache-vhost-export",
    ),
    path("webconfig/nginx/vhosts/", NginxVhostListView.as_view(), name="dashboard-nginx-vhost-list"),
    path(
        "webconfig/nginx/vhosts/export/",
        NginxVhostExportView.as_view(),
        name="dashboard-nginx-vhost-export",
    ),
    path("webconfig/<int:pk>/", WebConfigDetailView.as_view(), name="dashboard-webconfig-detail"),
    path("services/", WebServiceListView.as_view(), name="dashboard-webservice-list"),
    path("services/export/", ServiceExportView.as_view(), name="dashboard-service-export"),
    path("services/import/", ServiceImportView.as_view(), name="dashboard-service-import"),
    path(
        "services/import/confirm/",
        ServiceImportConfirmView.as_view(),
        name="dashboard-service-import-confirm",
    ),
    path(
        "services/<int:pk>/service/",
        WebServiceDomainServiceUpdateView.as_view(),
        name="dashboard-webservice-update",
    ),
    path(
        "services/container/<int:pk>/service/",
        ServiceContainerUpdateView.as_view(),
        name="dashboard-service-container-update",
    ),
    path("processes/", ProcessListView.as_view(), name="dashboard-process-list"),
    path("processes/export/", ProcessExportView.as_view(), name="dashboard-process-export"),
    path("processes/<int:pk>/", ProcessDetailView.as_view(), name="dashboard-process-detail"),
    path("was/", WasConfigListView.as_view(), name="dashboard-was-list"),
    path("was/export/", WasConfigExportView.as_view(), name="dashboard-was-export"),
    path("was/changes/", WasConfigHistoryListView.as_view(), name="dashboard-was-history"),
    path(
        "was/changes/export/",
        WasConfigHistoryExportView.as_view(),
        name="dashboard-was-history-export",
    ),
    path("was/jeus8/containers/", JeusContainerListView.as_view(), name="dashboard-jeus8-container-list"),
    path(
        "was/jeus8/containers/export/",
        JeusContainerExportView.as_view(),
        name="dashboard-jeus8-container-export",
    ),
    path("was/<int:pk>/", WasConfigDetailView.as_view(), name="dashboard-was-detail"),
    path("systems/", SystemListView.as_view(), name="dashboard-system-list"),
    path("systems/<int:pk>/", SystemDetailView.as_view(), name="dashboard-system-detail"),
    path(
        "systems/<int:pk>/manual-fields/",
        SystemHostManualFieldUpdateView.as_view(),
        name="dashboard-system-manual-fields-update",
    ),
    path("systems/export/", SystemHostExportView.as_view(), name="dashboard-system-export"),
    path("systems/import/", SystemHostImportView.as_view(), name="dashboard-system-import"),
    path(
        "systems/import/confirm/",
        SystemHostImportConfirmView.as_view(),
        name="dashboard-system-import-confirm",
    ),
]

api_urlpatterns = [
    path("assets/", AssetListAPIView.as_view(), name="api-asset-list"),
]
