# Generated by Django 6.0.7 on 2026-07-28 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_asset_last_changed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('match_pattern', models.CharField(help_text='ps -ef 원본 전체에 대한 정규식(re.search)', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_output', models.TextField()),
                ('collected_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='process_snapshot', to='core.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetectedApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_line', models.CharField(blank=True, max_length=1000)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='processes.applicationdefinition')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_applications', to='processes.processsnapshot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'definition'), name='unique_app_per_snapshot')],
            },
        ),
    ]
