# Generated by Django 6.0.7 on 2026-07-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdefinition',
            name='match_pattern',
            field=models.CharField(help_text='ps -ef 원본 전체에 대한 정규식(re.search). 예시:<br>· <code>postgres</code> — PostgreSQL 관련 프로세스(특수문자 없으면 단순 포함 검색과 동일하게 동작)<br>· <code>jeus\\.server\\.JEUSBooter</code> — JEUS 부트 클래스(마침표는 정규식에서 "아무 문자나"라 리터럴 점을 매칭하려면 <code>\\.</code>로 이스케이프)<br>· <code>ora_pmon_\\w+</code> — Oracle DB 인스턴스의 pmon 프로세스(인스턴스명은 SID마다 달라 <code>\\w+</code>로 아무 값이나 허용)<br>· <code>/app/webtob/bin/wsmond</code> — 특정 실행 경로 그대로(정규식 특수문자가 없으면 경로 문자열 자체를 써도 됨)', max_length=255),
        ),
    ]
