# Generated by Django 6.0.7 on 2026-07-24 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_asset_last_changed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebConfigSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('webtob', 'WebtoB')], max_length=20)),
                ('raw_content', models.TextField()),
                ('extra_sections', models.JSONField(blank=True, default=dict)),
                ('last_pushed_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_configs', to='core.asset')),
            ],
        ),
        migrations.CreateModel(
            name='WebtobNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('webtobdir', models.CharField(blank=True, max_length=255)),
                ('docroot', models.CharField(blank=True, max_length=255)),
                ('port', models.CharField(blank=True, max_length=20)),
                ('hth', models.CharField(blank=True, max_length=20)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='node', to='webconfig.webconfigsource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebtobSsl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('certificate_file', models.CharField(blank=True, max_length=500)),
                ('certificate_key_file', models.CharField(blank=True, max_length=500)),
                ('protocols', models.CharField(blank=True, max_length=255)),
                ('required_ciphers', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_entries', to='webconfig.webconfigsource')),
            ],
        ),
        migrations.CreateModel(
            name='WebtobSvrGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('svrtype', models.CharField(blank=True, max_length=50)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svrgroups', to='webconfig.webconfigsource')),
            ],
        ),
        migrations.CreateModel(
            name='WebtobServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('minproc', models.PositiveIntegerField(blank=True, null=True)),
                ('maxproc', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='webconfig.webconfigsource')),
                ('svrgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='webconfig.webtobsvrgroup')),
            ],
        ),
        migrations.CreateModel(
            name='WebtobVhost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('hostalias', models.CharField(blank=True, max_length=500)),
                ('docroot', models.CharField(blank=True, max_length=255)),
                ('port', models.CharField(blank=True, max_length=20)),
                ('ssl_flag', models.BooleanField(default=False)),
                ('logging', models.CharField(blank=True, max_length=100)),
                ('errorlog', models.CharField(blank=True, max_length=100)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vhosts', to='webconfig.webconfigsource')),
                ('ssl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vhosts', to='webconfig.webtobssl')),
            ],
        ),
        migrations.CreateModel(
            name='WebtobUri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('uri_path', models.CharField(blank=True, max_length=500)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uris', to='webconfig.webtobserver')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uris', to='webconfig.webconfigsource')),
                ('vhosts', models.ManyToManyField(blank=True, related_name='uris', to='webconfig.webtobvhost')),
            ],
        ),
        migrations.AddField(
            model_name='webtobsvrgroup',
            name='vhosts',
            field=models.ManyToManyField(blank=True, related_name='svrgroups', to='webconfig.webtobvhost'),
        ),
        migrations.AddConstraint(
            model_name='webconfigsource',
            constraint=models.UniqueConstraint(fields=('asset', 'kind'), name='unique_web_config_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='webtobssl',
            constraint=models.UniqueConstraint(fields=('source', 'name'), name='unique_ssl_name_per_source'),
        ),
        migrations.AddConstraint(
            model_name='webtobserver',
            constraint=models.UniqueConstraint(fields=('source', 'name'), name='unique_server_name_per_source'),
        ),
        migrations.AddConstraint(
            model_name='webtobvhost',
            constraint=models.UniqueConstraint(fields=('source', 'name'), name='unique_vhost_name_per_source'),
        ),
        migrations.AddConstraint(
            model_name='webtoburi',
            constraint=models.UniqueConstraint(fields=('source', 'name'), name='unique_uri_name_per_source'),
        ),
        migrations.AddConstraint(
            model_name='webtobsvrgroup',
            constraint=models.UniqueConstraint(fields=('source', 'name'), name='unique_svrgroup_name_per_source'),
        ),
    ]
