# Generated by Django 6.0.7 on 2026-07-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtobvhost',
            name='service_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
