# Generated by Django 6.0.7 on 2026-07-27 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0002_webtobvhost_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebServiceDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vhost_name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=255)),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_domains', to='webconfig.webconfigsource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'vhost_name', 'domain'), name='unique_service_domain')],
            },
        ),
    ]
