# Generated by Django 6.0.7 on 2026-07-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0003_webservicedomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='webconfigsource',
            name='solution_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='webservicedomain',
            name='port',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
