# Generated by Django 6.0.7 on 2026-07-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0004_webconfigsource_solution_version_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='webservicedomain',
            name='unique_service_domain',
        ),
        migrations.AddField(
            model_name='webservicedomain',
            name='aliases',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddConstraint(
            model_name='webservicedomain',
            constraint=models.UniqueConstraint(fields=('source', 'vhost_name'), name='unique_service_domain'),
        ),
    ]
