# Generated by Django 6.0.7 on 2026-07-27 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0005_remove_webservicedomain_unique_service_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebConfigSourceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_content', models.TextField()),
                ('new_content', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='webconfig.webconfigsource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
