# Generated by Django 6.0.7 on 2026-07-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0006_webconfigsourcerevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='webconfigsource',
            name='solution_fix',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
