# Generated by Django 6.0.7 on 2026-07-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0007_webconfigsource_solution_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtobnode',
            name='limit_request_body',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
