# Generated by Django 6.0.7 on 2026-07-29 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0008_webtobnode_limit_request_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webconfigsource',
            name='kind',
            field=models.CharField(choices=[('webtob', 'WebtoB'), ('apache', 'Apache'), ('nginx', 'Nginx')], max_length=20),
        ),
        migrations.CreateModel(
            name='ApacheVhost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('hostalias', models.CharField(blank=True, max_length=500)),
                ('port', models.CharField(blank=True, max_length=20)),
                ('docroot', models.CharField(blank=True, max_length=255)),
                ('ssl_flag', models.BooleanField(default=False)),
                ('ssl_certificate_file', models.CharField(blank=True, max_length=500)),
                ('ssl_certificate_key_file', models.CharField(blank=True, max_length=500)),
                ('logging', models.CharField(blank=True, max_length=255)),
                ('errorlog', models.CharField(blank=True, max_length=255)),
                ('proxy_summary', models.TextField(blank=True)),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apache_vhosts', to='webconfig.webconfigsource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'name'), name='unique_apache_vhost_name_per_source')],
            },
        ),
        migrations.CreateModel(
            name='NginxVhost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('hostalias', models.CharField(blank=True, max_length=500)),
                ('port', models.CharField(blank=True, max_length=20)),
                ('listen', models.CharField(blank=True, max_length=255)),
                ('docroot', models.CharField(blank=True, max_length=255)),
                ('ssl_flag', models.BooleanField(default=False)),
                ('ssl_certificate_file', models.CharField(blank=True, max_length=500)),
                ('ssl_certificate_key_file', models.CharField(blank=True, max_length=500)),
                ('logging', models.CharField(blank=True, max_length=255)),
                ('errorlog', models.CharField(blank=True, max_length=255)),
                ('proxy_summary', models.TextField(blank=True)),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nginx_vhosts', to='webconfig.webconfigsource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'name'), name='unique_nginx_vhost_name_per_source')],
            },
        ),
    ]
