# Generated by Django 6.0.7 on 2026-07-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0009_alter_webconfigsource_kind_apachevhost_nginxvhost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtobvhost',
            name='errorlog',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='webtobvhost',
            name='logging',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
