# Generated by Django 6.0.7 on 2026-07-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0010_alter_webtobvhost_errorlog_alter_webtobvhost_logging'),
    ]

    operations = [
        migrations.AddField(
            model_name='apachevhost',
            name='ssl_ciphers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='apachevhost',
            name='ssl_protocols',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nginxvhost',
            name='ssl_ciphers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nginxvhost',
            name='ssl_protocols',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
