# Generated by Django 6.0.7 on 2026-07-31 11:23

import django.db.models.deletion
from django.db import migrations, models


def migrate_service_name_to_service(apps, schema_editor):
    """기존 자유 텍스트 service_name 값을 core.Service 행으로 이관하고 새 FK에 연결한다.
    같은 이름 문자열은 앱 구분 없이 하나의 Service로 합쳐진다(WebToB<->JEUS 서비스 전파가
    성립하려면 애초에 같은 Service를 가리켜야 하므로)."""
    Service = apps.get_model("core", "Service")
    service_by_name: dict[str, int] = {}

    def resolve(name: str) -> int | None:
        name = (name or "").strip()
        if not name:
            return None
        if name not in service_by_name:
            service, _ = Service.objects.get_or_create(name=name)
            service_by_name[name] = service.id
        return service_by_name[name]

    for model_name in ["WebtobVhost", "ApacheVhost", "NginxVhost"]:
        model = apps.get_model("webconfig", model_name)
        names = (
            model.objects.exclude(service_name="")
            .values_list("service_name", flat=True)
            .distinct()
        )
        for name in names:
            service_id = resolve(name)
            if service_id is not None:
                model.objects.filter(service_name=name).update(service_id=service_id)


def noop_reverse(apps, schema_editor):
    """역방향은 service_name 컬럼이 이미 없는 시점에는 되돌릴 원본 문자열이 없어 손실 없이
    되감을 방법이 없다 - RemoveField의 역방향(AddField)이 컬럼을 다시 만든 뒤에는 그냥
    빈 값으로 둔다(이 마이그레이션 자체를 롤백하는 드문 경우에만 해당)."""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service'),
        ('webconfig', '0011_apachevhost_ssl_ciphers_apachevhost_ssl_protocols_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apachevhost',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apache_vhosts', to='core.service'),
        ),
        migrations.AddField(
            model_name='nginxvhost',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nginx_vhosts', to='core.service'),
        ),
        migrations.AddField(
            model_name='webtobvhost',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webtob_vhosts', to='core.service'),
        ),
        migrations.RunPython(migrate_service_name_to_service, noop_reverse),
        migrations.RemoveField(
            model_name='apachevhost',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='nginxvhost',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='webtobvhost',
            name='service_name',
        ),
    ]
