# Generated by Django 6.0.7 on 2026-08-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0013_alter_webconfigsource_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='webconfigsource',
            name='config_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
