# Generated by Django 6.0.7 on 2026-08-14 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbConfigSourceFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='AUTO: DbConfigSource.extra 안의 dot-path(kind_key_overrides에 없는 kind는 이 경로를 씀), 예: force_logging / MANUAL: extra와 무관한 고유 식별자', max_length=255, unique=True)),
                ('kind_key_overrides', models.JSONField(blank=True, default=dict, help_text='AUTO 전용(선택). kind별로 key와 다른 경로를 써야 할 때만 채움. 예: {"oracle": "supplemental_log_data_min"}')),
                ('label', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('bool', 'Boolean'), ('choice', '선택형')], default='text', max_length=10)),
                ('source', models.CharField(choices=[('auto', '자동 (extra에서 추출)'), ('manual', '수기 입력')], default='auto', max_length=10)),
                ('is_visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DbConfigSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('oracle', 'Oracle')], max_length=20)),
                ('db_unique_name', models.CharField(max_length=128)),
                ('db_name', models.CharField(blank=True, max_length=128)),
                ('database_role', models.CharField(blank=True, max_length=30)),
                ('open_mode', models.CharField(blank=True, max_length=30)),
                ('log_mode', models.CharField(blank=True, max_length=20)),
                ('characterset', models.CharField(blank=True, max_length=60)),
                ('platform_name', models.CharField(blank=True, max_length=100)),
                ('db_created_at', models.DateTimeField(blank=True, null=True)),
                ('raw_content', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('last_pushed_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='db_config_sources', to='core.asset')),
            ],
        ),
        migrations.CreateModel(
            name='DbConfigSourceFieldChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='database.dbconfigsourcefielddefinition')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DbConfigSourceFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=500, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.dbconfigsourcefielddefinition')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='database.dbconfigsource')),
            ],
        ),
        migrations.CreateModel(
            name='DbConfigSourceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_content', models.TextField()),
                ('new_content', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='database.dbconfigsource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DbInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance_name', models.CharField(max_length=30)),
                ('instance_number', models.PositiveIntegerField(blank=True, null=True)),
                ('host_name', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('archiver', models.CharField(blank=True, max_length=20)),
                ('startup_time', models.DateTimeField(blank=True, null=True)),
                ('listener_port', models.CharField(blank=True, max_length=10)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='db_instances', to='core.asset')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='database.dbconfigsource')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dbconfigsource',
            constraint=models.UniqueConstraint(fields=('kind', 'db_unique_name'), name='unique_db_config_source'),
        ),
        migrations.AddConstraint(
            model_name='dbconfigsourcefieldchoice',
            constraint=models.UniqueConstraint(fields=('field_definition', 'value'), name='unique_db_config_source_field_choice'),
        ),
        migrations.AddConstraint(
            model_name='dbconfigsourcefieldvalue',
            constraint=models.UniqueConstraint(fields=('source', 'field_definition'), name='unique_db_config_source_field_value'),
        ),
        migrations.AddConstraint(
            model_name='dbinstance',
            constraint=models.UniqueConstraint(fields=('source', 'instance_name'), name='unique_db_instance_name_per_source'),
        ),
    ]
