# Generated by Django 6.0.7 on 2026-08-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asset_manual_services'),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbconfigsource',
            name='manual_services',
            field=models.ManyToManyField(blank=True, related_name='manual_db_config_sources', to='core.service'),
        ),
    ]
