# Generated by Django 6.0.7 on 2026-09-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_dbconfigsource_manual_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbconfigsource',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dbconfigsource',
            name='kind',
            field=models.CharField(choices=[('oracle', 'Oracle'), ('manual', '수기 등록')], max_length=20),
        ),
    ]
