# Generated by Django 6.0.7 on 2026-07-31 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_asset_last_changed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHostFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='SystemHost.extra 안의 dot-path(kind_key_overrides에 없는 kind는 이 경로를 씀). 예: host_summary.hardware.cpu.count', max_length=255, unique=True)),
                ('kind_key_overrides', models.JSONField(blank=True, default=dict, help_text='kind(vcenter/nutanix)별로 key와 다른 경로를 써야 할 때만 채움. 예: {"nutanix": "host.num_cpu_cores"} (vCenter는 key를 그대로 씀)')),
                ('label', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('bool', 'Boolean')], default='text', max_length=10)),
                ('is_visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SystemSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('vcenter', 'vCenter'), ('nutanix', 'Nutanix')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('last_pushed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'name'), name='unique_system_source_per_kind')],
            },
        ),
        migrations.CreateModel(
            name='SystemHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='systems.systemsource')),
            ],
        ),
        migrations.CreateModel(
            name='SystemVm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('uuid', models.CharField(blank=True, max_length=100)),
                ('power_state', models.CharField(blank=True, max_length=50)),
                ('num_cpu', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('primary_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('tools_status', models.CharField(blank=True, max_length=50)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_vms', to='core.asset')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vms', to='systems.systemhost')),
            ],
        ),
        migrations.CreateModel(
            name='SystemNic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('network_name', models.CharField(blank=True, max_length=255)),
                ('is_connected', models.BooleanField(default=True)),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nics', to='systems.systemvm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemDisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('size_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('storage_name', models.CharField(blank=True, max_length=255)),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disks', to='systems.systemvm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemHostFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=500, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.systemhostfielddefinition')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='systems.systemhost')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('host', 'field_definition'), name='unique_system_host_field_value')],
            },
        ),
        migrations.AddConstraint(
            model_name='systemhost',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_system_host_external_id_per_source'),
        ),
        migrations.AddConstraint(
            model_name='systemvm',
            constraint=models.UniqueConstraint(fields=('host', 'uuid'), name='unique_system_vm_uuid_per_host'),
        ),
    ]
