# Generated by Django 6.0.7 on 2026-07-31 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemhostfielddefinition',
            name='source',
            field=models.CharField(choices=[('auto', '자동 (extra에서 추출)'), ('manual', '수기 입력')], default='auto', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemhostfielddefinition',
            name='key',
            field=models.CharField(help_text='AUTO: SystemHost.extra 안의 dot-path(kind_key_overrides에 없는 kind는 이 경로를 씀), 예: host_summary.hardware.cpu.count / MANUAL: extra와 무관한 고유 식별자', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='systemhostfielddefinition',
            name='kind_key_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='AUTO 전용(선택). kind(vcenter/nutanix)별로 key와 다른 경로를 써야 할 때만 채움. 예: {"nutanix": "host.num_cpu_cores"} (vCenter는 key를 그대로 씀)'),
        ),
        migrations.AlterField(
            model_name='systemhostfielddefinition',
            name='value_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('bool', 'Boolean'), ('choice', '선택형')], default='text', max_length=10),
        ),
        migrations.CreateModel(
            name='SystemHostFieldChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='systems.systemhostfielddefinition')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('field_definition', 'value'), name='unique_system_host_field_choice')],
            },
        ),
    ]
