# Generated by Django 6.0.7 on 2026-07-31 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_systemhostfielddefinition_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemvm',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vms', to='systems.systemsource'),
            preserve_default=False,
        ),
    ]
