# Generated by Django 6.0.7 on 2026-08-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_systemvm_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsource',
            name='kind',
            field=models.CharField(choices=[('vcenter', 'vCenter'), ('nutanix', 'Nutanix'), ('physical', '물리(수기 등록)')], max_length=20),
        ),
    ]
