# Generated by Django 6.0.7 on 2026-08-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asset_manual_services'),
        ('systems', '0004_alter_systemsource_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemhost',
            name='manual_services',
            field=models.ManyToManyField(blank=True, related_name='manual_system_hosts', to='core.service'),
        ),
    ]
